// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const defaultDatabaseUrl = "mysql://root:root@localhost:3306/uniforma";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Allow `prisma generate` during install even before local env secrets exist.
    url: process.env.DATABASE_URL ?? defaultDatabaseUrl,
  },
});
