CREATE TABLE `ajustepagopedido` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(191) NOT NULL,
  `requestId` VARCHAR(191) NOT NULL,
  `pedidoId` INTEGER NOT NULL,
  `pagoOriginalId` INTEGER NOT NULL,
  `pagoGeneradoId` INTEGER NULL,
  `cierreOriginalId` INTEGER NULL,
  `cierreRectificadoId` INTEGER NULL,
  `montoRegistrado` DOUBLE NOT NULL,
  `montoCorrecto` DOUBLE NOT NULL,
  `diferencia` DOUBLE NOT NULL,
  `fechaPagoReal` DATETIME(3) NOT NULL,
  `metodo` VARCHAR(191) NOT NULL,
  `referencia` VARCHAR(191) NULL,
  `banco` VARCHAR(191) NULL,
  `ubicacion` VARCHAR(191) NULL,
  `motivo` MEDIUMTEXT NOT NULL,
  `evidenciaReferencia` MEDIUMTEXT NOT NULL,
  `estado` VARCHAR(191) NOT NULL DEFAULT 'pendiente',
  `aprobacionesRequeridas` INTEGER NOT NULL DEFAULT 1,
  `solicitadoPorId` INTEGER NOT NULL,
  `aprobadoPorId` INTEGER NULL,
  `segundaAprobacionPorId` INTEGER NULL,
  `respuesta` MEDIUMTEXT NULL,
  `creadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actualizadoEn` DATETIME(3) NOT NULL,
  `aprobadoEn` DATETIME(3) NULL,
  `segundaAprobacionEn` DATETIME(3) NULL,
  `aplicadoEn` DATETIME(3) NULL,

  UNIQUE INDEX `ajustepagopedido_folio_key`(`folio`),
  UNIQUE INDEX `ajustepagopedido_requestId_key`(`requestId`),
  UNIQUE INDEX `ajustepagopedido_pagoGeneradoId_key`(`pagoGeneradoId`),
  INDEX `ajustepagopedido_pedidoId_creadoEn_idx`(`pedidoId`, `creadoEn`),
  INDEX `ajustepagopedido_pagoOriginalId_idx`(`pagoOriginalId`),
  INDEX `ajustepagopedido_estado_creadoEn_idx`(`estado`, `creadoEn`),
  INDEX `ajustepagopedido_solicitadoPorId_creadoEn_idx`(`solicitadoPorId`, `creadoEn`),
  INDEX `ajustepagopedido_cierreOriginalId_idx`(`cierreOriginalId`),
  INDEX `ajustepagopedido_cierreRectificadoId_idx`(`cierreRectificadoId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `ajustepagopedido`
  ADD CONSTRAINT `ajustepagopedido_pedidoId_fkey` FOREIGN KEY (`pedidoId`) REFERENCES `PedidoProduccion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `ajustepagopedido_pagoOriginalId_fkey` FOREIGN KEY (`pagoOriginalId`) REFERENCES `PagoPedido`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `ajustepagopedido_pagoGeneradoId_fkey` FOREIGN KEY (`pagoGeneradoId`) REFERENCES `PagoPedido`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `ajustepagopedido_solicitadoPorId_fkey` FOREIGN KEY (`solicitadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `ajustepagopedido_aprobadoPorId_fkey` FOREIGN KEY (`aprobadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `ajustepagopedido_segundaAprobacionPorId_fkey` FOREIGN KEY (`segundaAprobacionPorId`) REFERENCES `Usuario`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
