export interface PermissionDefinition {
  key: string;
  label: string;
  description: string;
  category: string;
}

export const PERMISSION_CATALOG: PermissionDefinition[] = [
  { key: 'dashboard.view', label: 'Dashboard', description: 'Ver dashboard principal', category: 'General' },
  {
    key: 'dashboard.filtro-vendedor',
    label: 'Dashboard por vendedor',
    description: 'Cambiar el vendedor consultado en el dashboard operativo',
    category: 'General',
  },
  {
    key: 'dashboard.filtro-tienda',
    label: 'Dashboard por tienda',
    description: 'Cambiar la tienda consultada en el dashboard operativo',
    category: 'General',
  },
  {
    key: 'dashboard.ver-todo',
    label: 'Dashboard consolidado',
    description: 'Ver el dashboard consolidado de todos los vendedores y tiendas',
    category: 'General',
  },
  { key: 'ventas.view', label: 'Ventas', description: 'Ver modulo de ventas', category: 'Ventas' },
  { key: 'ventas.manage', label: 'Gestionar ventas', description: 'Crear y operar ventas', category: 'Ventas' },
  { key: 'cotizaciones.view', label: 'Cotizaciones', description: 'Ver modulo de cotizaciones', category: 'Ventas' },
  { key: 'cotizaciones.manage', label: 'Gestionar cotizaciones', description: 'Crear y operar cotizaciones', category: 'Ventas' },
  { key: 'postventa.view', label: 'Cambios y devoluciones', description: 'Ver cambios y devoluciones', category: 'Ventas' },
  {
    key: 'postventa.manage',
    label: 'Gestionar cambios y devoluciones',
    description: 'Crear y operar cambios y devoluciones',
    category: 'Ventas',
  },
  { key: 'productos.view', label: 'Productos', description: 'Ver productos', category: 'Productos' },
  { key: 'productos.manage', label: 'Gestionar productos', description: 'Crear, editar y eliminar productos', category: 'Productos' },
  { key: 'inventario.ingreso.view', label: 'Ingreso inventario', description: 'Ver ingresos de inventario', category: 'Inventario' },
  { key: 'inventario.resumen.view', label: 'Resumen inventario', description: 'Ver resumen de inventario', category: 'Inventario' },
  { key: 'inventario.traslados.view', label: 'Traslados', description: 'Ver traslados de inventario', category: 'Inventario' },
  { key: 'inventario.telas.view', label: 'Inventario de telas', description: 'Ver rollos, movimientos y consumo estimado de telas', category: 'Inventario' },
  { key: 'inventario.telas.manage', label: 'Gestionar inventario de telas', description: 'Crear rollos, movimientos y consumos estimados de tela', category: 'Inventario' },
  { key: 'inventario.multi-bodega', label: 'Inventario multi bodega', description: 'Ver y operar inventario de varias bodegas', category: 'Inventario' },
  { key: 'inventario.vender-otras-bodegas', label: 'Vender desde otras bodegas', description: 'Usar bodegas visibles para vendedores, como disparejos', category: 'Inventario' },
  { key: 'inventario.ajustar', label: 'Ajustar inventario', description: 'Registrar ingresos o ajustes de inventario en bodegas autorizadas', category: 'Inventario' },
  { key: 'inventario.trasladar', label: 'Trasladar inventario', description: 'Trasladar inventario entre bodegas autorizadas', category: 'Inventario' },
  { key: 'inventario.ver-costos', label: 'Ver costos de inventario', description: 'Consultar costos y valores de inventario', category: 'Inventario' },
  { key: 'bodegas.view', label: 'Bodegas', description: 'Ver modulo de bodegas', category: 'Gestion' },
  { key: 'bodegas.manage', label: 'Gestionar bodegas', description: 'Crear, editar y eliminar bodegas', category: 'Gestion' },
  { key: 'bodegas.assign', label: 'Asignar bodegas', description: 'Asignar bodegas adicionales a usuarios', category: 'Gestion' },
  { key: 'proveedores.view', label: 'Proveedores', description: 'Ver catalogo de proveedores', category: 'Gestion' },
  { key: 'proveedores.manage', label: 'Gestionar proveedores', description: 'Crear, editar y eliminar proveedores', category: 'Gestion' },
  { key: 'proveedores.facturas.view', label: 'Facturas proveedores', description: 'Ver facturas cargadas de proveedores', category: 'Gestion' },
  { key: 'proveedores.facturas.manage', label: 'Gestionar facturas proveedores', description: 'Cargar, editar y eliminar facturas de proveedores', category: 'Gestion' },
  { key: 'produccion.view', label: 'Produccion', description: 'Ver pedidos de produccion', category: 'Produccion' },
  { key: 'produccion.manage', label: 'Gestionar produccion', description: 'Crear y operar pedidos de produccion', category: 'Produccion' },
  {
    key: 'produccion.unificar',
    label: 'Unificar pedidos',
    description: 'Mostrar y usar la accion para generar pedidos unificados',
    category: 'Permisos especiales',
  },
  { key: 'bordados.view', label: 'Bordados', description: 'Ver modulo de bordados', category: 'Bordados' },
  {
    key: 'bordados.manage',
    label: 'Gestionar bordados',
    description: 'Actualizar estado y fecha estimada de bordados',
    category: 'Bordados',
  },
  { key: 'tracking.view', label: 'Tracking pedidos', description: 'Ver modulo de tracking de pedidos', category: 'Produccion' },
  {
    key: 'tracking.manage',
    label: 'Gestionar tracking',
    description: 'Reenviar correos de tracking de pedidos',
    category: 'Produccion',
  },
  { key: 'pagos.view', label: 'Pagos', description: 'Ver modulo de pagos', category: 'Pagos' },
  { key: 'pagos.manage', label: 'Gestionar pagos', description: 'Crear y operar pagos', category: 'Pagos' },
  { key: 'envios.view', label: 'Envios', description: 'Ver modulo de envios', category: 'Ventas' },
  { key: 'envios.manage', label: 'Gestionar envios', description: 'Crear y actualizar envios', category: 'Ventas' },
  { key: 'clientes.view', label: 'Clientes', description: 'Ver clientes', category: 'Gestion' },
  { key: 'clientes.manage', label: 'Gestionar clientes', description: 'Crear, editar y eliminar clientes', category: 'Gestion' },
  { key: 'usuarios.view', label: 'Usuarios', description: 'Ver usuarios', category: 'Gestion' },
  { key: 'usuarios.manage', label: 'Gestionar usuarios', description: 'Crear, editar y eliminar usuarios', category: 'Gestion' },
  { key: 'roles.view', label: 'Roles', description: 'Ver panel de roles', category: 'Gestion' },
  { key: 'roles.manage', label: 'Gestionar roles', description: 'Crear, editar y eliminar roles', category: 'Gestion' },
  {
    key: 'sistema.multi-tienda',
    label: 'Filtros multi-tienda',
    description: 'Usar filtros y selectores de tienda o bodega en pantallas operativas',
    category: 'Permisos especiales',
  },
  {
    key: 'sistema.selector-vendedores',
    label: 'Selector de vendedores',
    description: 'Elegir vendedor en pantallas y reportes habilitados',
    category: 'Permisos especiales',
  },
  { key: 'correlativos.view', label: 'Correlativos', description: 'Ver panel de correlativos', category: 'Gestion' },
  {
    key: 'correlativos.manage',
    label: 'Gestionar correlativos',
    description: 'Modificar abreviaturas y contadores de correlativos',
    category: 'Gestion',
  },
  { key: 'admin.view', label: 'Configuracion', description: 'Ver panel de configuracion', category: 'Gestion' },
  { key: 'admin.manage', label: 'Gestionar configuracion', description: 'Modificar configuraciones del sistema', category: 'Gestion' },
  { key: 'logs.view', label: 'Auditoria', description: 'Ver panel de auditoria y logs de acciones', category: 'Gestion' },
  { key: 'correcciones.view', label: 'Correcciones', description: 'Ver correcciones controladas de documentos', category: 'Gestion' },
  {
    key: 'correcciones.manage',
    label: 'Gestionar correcciones',
    description: 'Aplicar correcciones controladas con motivo y auditoria',
    category: 'Gestion',
  },
  {
    key: 'whatsapp.manage',
    label: 'WhatsApp Business',
    description: 'Configurar numeros e identificadores de WhatsApp Business por vendedor',
    category: 'Gestion',
  },
  { key: 'metas.view', label: 'Metas mensuales', description: 'Ver metas mensuales por tienda o vendedor', category: 'Reportes' },
  {
    key: 'metas.manage',
    label: 'Gestionar metas mensuales',
    description: 'Crear y modificar metas mensuales por tienda o vendedor',
    category: 'Reportes',
  },
  { key: 'reportes.ventas-diarias.view', label: 'Ventas diarias', description: 'Ver reporte de ventas diarias', category: 'Reportes' },
  { key: 'reportes.reporte-diario.view', label: 'Reporte diario', description: 'Ver reporte diario', category: 'Reportes' },
  {
    key: 'reportes.reporte-diario.generar-ajeno',
    label: 'Generar cierre diario de otro vendedor',
    description: 'Permite seleccionar vendedor, fecha libre y omitir correo al generar cierres diarios',
    category: 'Reportes',
  },
  { key: 'reportes.reporte-quincenal.view', label: 'Reporte quincenal', description: 'Ver reporte quincenal', category: 'Reportes' },
  {
    key: 'reportes.ventas-producto.view',
    label: 'Ventas por producto',
    description: 'Ver reporte de ventas por producto',
    category: 'Reportes',
  },
  { key: 'reportes.top-clientes.view', label: 'Top clientes', description: 'Ver reporte de top clientes', category: 'Reportes' },
  {
    key: 'reportes.ingresos.view',
    label: 'Ingresos de inventario',
    description: 'Ver reporte de ingresos de inventario',
    category: 'Reportes',
  },
  { key: 'reportes.traslados.view', label: 'Reporte de traslados', description: 'Ver reporte de traslados', category: 'Reportes' },
  { key: 'reportes.stock-bajo.view', label: 'Stock bajo', description: 'Ver reporte de stock bajo', category: 'Reportes' },
  {
    key: 'reportes.produccion-unificados.view',
    label: 'Unificados produccion',
    description: 'Ver reporte de produccion unificada',
    category: 'Reportes',
  },
  {
    key: 'reportes.comparativo-tiendas.view',
    label: 'Comparativo tiendas',
    description: 'Ver comparativo operativo entre tiendas',
    category: 'Reportes',
  },
];
